version: '2.1'
setup: true

orbs:
  rusty: bencord0/rusty-orb@1.1.0

default-executor: &default-executor
  # https://circleci.com/docs/configuration-reference/#executor-job
  docker:
    - image: cimg/rust:1.64

  # machine:
  #   ...
  # macos:
  #   ...

jobs:
  setup:
    <<: *default-executor
    steps:
      - checkout
      - run:
          name: Generate config
          command: |
            mkdir -pv generated-config
            cargo run --bin generate_pipeline | tee generated-config/config.yml
            echo "to: ${CIRCLE_USERNAME}" > generated-config/parameters.yml
      - persist_to_workspace:
          root: .
          paths: [generated-config]

workflows:
  setup:
    jobs:
      - setup
      - rusty/continue:
          # relative to workspace root
          configuration: ./generated-config/config.yml
          parameters: ./generated-config/parameters.yml
          requires: [setup]
